// 6-letter words
export const words6: string[] = [
  'ABACUS', 'ABDUCT', 'ABJECT', 'ABLAZE', 'ABOUND', 'ABROAD', 'ABSORB', 'ABSURD', 'ACCEPT', 'ACCORD',
  'ACCUSE', 'ACROSS', 'ACTIVE', 'ADAPTS', 'ADDICT', 'ADHERE', 'ADJUST', 'ADMIRE', 'ADVICE', 'ADVISE',
  'AFFECT', 'AFFORD', 'AFRAID', 'AGENCY', 'AGENDA', 'AGENTS', 'AGREED', 'AISLES', 'ALBUMS', 'ALCOVE',
  'ALERTS', 'ALIENS', 'ALIGHT', 'ALIGNS', 'ALLEYS', 'ALLIED', 'ALLIES', 'ALLOTS', 'ALLOWS', 'ALMOND',
  'ALMOST', 'ALPINE', 'ALWAYS', 'AMAZED', 'AMAZES', 'AMENDS', 'AMIDST', 'AMOUNT', 'ANCHOR', 'ANGLES'
];

