// 7-letter words
export const words7: string[] = [
  'ABILITY', 'ABSENCE', 'ACADEMY', 'ACCOUNT', 'ACHIEVE', 'ACQUIRE', 'ADDRESS', 'ADVANCE', 'ADVERSE', 'ADVISED',
  'ADVISER', 'AFFECTS', 'AFFORDS', 'AGAINST', 'AGREING', 'ALCOHOL', 'ALERTED', 'ALIASES', 'ALIGNED', 'ALLEGES',
  'ALLEGED', 'ALLERGY', 'ALLOWED', 'ALREADY', 'ALTERED', 'AMAZING', 'AMBIENT', 'AMENDED', 'AMONGST', 'AMOUNTS',
  'ANALOGY', 'ANALYSE', 'ANALYZE', 'ANCHORS', 'ANCIENT', 'ANGLING', 'ANIMALS', 'ANNUALS', 'ANNUITY', 'ANOMALY',
  'ANOTHER', 'ANSWERS', 'ANTENNA', 'ANTIQUE', 'ANXIETY', 'ANYBODY', 'ANYMORE', 'ANYTIME', 'APPEALS', 'APPEARS'
];

