// 8-letter words
export const words8: string[] = [
  'ABANDONS', 'ABERRANT', 'ABNORMAL', 'ABORTIVE', 'ABRASIVE', 'ABRIDGED', 'ABSOLUTE', 'ABSTRACT', 'ACADEMIC', 'ACCENTED',
  'ACCEPTED', 'ACCESSED', 'ACCIDENT', 'ACCORDED', 'ACCURACY', 'ACCURATE', 'ACHIEVED', 'ACHIEVES', 'ACOUSTIC', 'ACQUIRED',
  'ACQUIRES', 'ACTIVITY', 'ACTUALLY', 'ADAPTIVE', 'ADDICTED', 'ADDITION', 'ADEQUATE', 'ADHERENT', 'ADJACENT', 'ADJUSTED',
  'ADMIRERS', 'ADMIRING', 'ADMITTED', 'ADOPTING', 'ADOPTION', 'ADVANCED', 'ADVANCES', 'ADVANTAGE', 'ADVISERS', 'ADVISING',
  'ADVISERS', 'ADVISING', 'ADVISORY', 'AFFECTED', 'AFFORDED', 'AGENCIES', 'AGITATED', 'AGREEING', 'AIRBORNE', 'AIRFARES'
];

